# Generated by Django 5.1.3 on 2024-11-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='family_name',
            field=models.IntegerField(default=0, verbose_name='性'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.IntegerField(default=0, verbose_name='名前'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
