# Generated by Django 5.1.3 on 2024-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='family_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='性'),
        ),
    ]
