# Generated by Django 5.1.3 on 2024-11-08 21:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitene', '0005_toppage_footer_text_navitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navitems',
            name='top_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_items', to='mitene.toppage'),
        ),
    ]
