# Generated by Django 5.1.3 on 2024-11-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitene', '0008_postcategory_tag_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
