# Generated by Django 5.1.3 on 2024-11-09 15:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitene', '0009_remove_blogpage_page_ptr_delete_blogindexpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plainpage',
            name='main_body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
