# Generated by Django 5.1.3 on 2024-11-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitene', '0011_alter_postpage_main_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlainPage',
        ),
    ]
